### PR TITLE
fix variable NaN comparisons

### LINKED ISSUE #5040: `NaN != any_float_value` should evaluate to true for variable NaN values
### Context
	Odin:    dev-2025-04:6045955c8
	Backend: LLVM 20.1.2

### Expected Behavior
This is the same issue as in #5038, but it also needs to be addressed for variable NaNs, not just constant ones.

In the IEEE-754 standard, the expression `NaN != x` should always evaluate to `true`, where `x` can be any floating-point value, including Inf, NaN, etc.

### Current Behavior
Currently such a comparison returns `false`.

### Failure Information
So these tests should pass:

```odin
package test_internal

import "core:testing"

@(test)
compare_variable_nans_f32 :: proc(t: ^testing.T) {
	NaN     := f32(0h7fc0_0000)
	NaN2    := f32(0h7fc0_0001)
	Inf     :: f32(0h7F80_0000)
	Neg_Inf :: f32(0hFF80_0000)

	testing.expect_value(t, NaN == NaN,     false)
	testing.expect_value(t, NaN == NaN2,    false)
	testing.expect_value(t, NaN != 0,       true)
	testing.expect_value(t, NaN != 5,       true)
	testing.expect_value(t, NaN != -5,      true)
	testing.expect_value(t, NaN != NaN,     true)
	testing.expect_value(t, NaN != NaN2,    true)
	testing.expect_value(t, NaN != Inf,     true)
	testing.expect_value(t, NaN != Neg_Inf, true)
	testing.expect_value(t, NaN <  NaN,     false)
	testing.expect_value(t, NaN <= NaN,     false)
	testing.expect_value(t, NaN >  NaN,     false)
	testing.expect_value(t, NaN >= NaN,     false)
}

@(test)
compare_variable_nans_f64 :: proc(t: ^testing.T) {
	NaN     := f64(0h7fff_0000_0000_0000)
	NaN2    := f64(0h7fff_0000_0000_0001)
	Inf     :: f64(0h7FF0_0000_0000_0000)
	Neg_Inf :: f64(0hFFF0_0000_0000_0000)

	testing.expect_value(t, NaN == NaN,     false)
	testing.expect_value(t, NaN == NaN2,    false)
	testing.expect_value(t, NaN != 0,       true)
	testing.expect_value(t, NaN != 5,       true)
	testing.expect_value(t, NaN != -5,      true)
	testing.expect_value(t, NaN != NaN,     true)
	testing.expect_value(t, NaN != NaN2,    true)
	testing.expect_value(t, NaN != Inf,     true)
	testing.expect_value(t, NaN != Neg_Inf, true)
	testing.expect_value(t, NaN <  NaN,     false)
	testing.expect_value(t, NaN <= NaN,     false)
	testing.expect_value(t, NaN >  NaN,     false)
	testing.expect_value(t, NaN >= NaN,     false)
}

```

### PR DESCRIPTION
**Pull request by laytan**
Fixes #5040

### CODE REVIEW

File: src/llvm_backend_proc.cpp [hunk 1]
```diff
@@ -1442,7 +1442,7 @@ gb_internal lbValue lb_build_builtin_simd_proc(lbProcedure *p, Ast *expr, TypeAn
 			LLVMRealPredicate pred = cast(LLVMRealPredicate)0;
 			switch (builtin_id) {
 			case BuiltinProc_simd_lanes_eq: pred = LLVMRealOEQ; break;
```
Comment (gingerBill) [inline src/llvm_backend_proc.cpp:1444]: Should `==` also be `LLVMRealUEQ`?
