### PR TITLE
Fix compiler segfault when trying to use () as type

### LINKED ISSUE #5621: Compiler segfault when trying to use () as type
## Context

* Operating System & Odin Version: Windows 11, dev-2025-08-nightly:accdd7c
* `odin report` output:
        Odin:    dev-2025-08-nightly:accdd7c
        OS:      Windows 11 Professional (version: 23H2), build 22631.5768
        CPU:     12th Gen Intel(R) Core(TM) i7-12700H
        RAM:     32492 MiB
        Backend: LLVM 20.1.0

## Expected Behavior

Probably a compiler error saying () isn't a type, or maybe a parse error

## Current Behavior

Segmentation fault

## Failure Information (for bugs)

N/A

### Steps to Reproduce

Make a file called `bug.odin` with the following contents
```odin
package main

a: () = 1
```
then run
```bash
odin build bug.odin -file
```

### Failure Logs

Segmentation fault

### PR DESCRIPTION
**Pull request by smoke-y**
Fixes #5621

### CODE REVIEW

File: src/checker.cpp [hunk 1]
```diff
@@ -1797,6 +1797,7 @@ gb_internal void add_type_and_value(CheckerContext *ctx, Ast *expr, AddressingMo
 		}
 
 		expr = unparen_expr(expr);
+		if(!expr) break;
```
Comment (gingerBill) [inline src/checker.cpp]:
```cpp
if (expr == nullptr) {
        break;
}
```
