### PR TITLE
Fix fields_wait_signal futex.

### LINKED ISSUE #2463: Parapoly Types are type checked incorrectly due to race condition
* Operating System & Odin Version:
        Odin: dev-2023-04:b42bb5be
        OS:   Windows 10 Home Basic (version: 21H2), build 19044.2728
        CPU:  AMD Ryzen 7 5800X 8-Core Processor
        RAM:  32711 MiB

The type checker will randomly fail with a parapoly type due to a race condition. An error will be reported that a field is missing.
I can only reproduce this with parapoly types that are defined in separate procedures.
Take the following minimal failure case:
```odin
package will_eventually_fail

Foo :: struct($N: int) {
    a: u32,
}

bar :: proc(foo: ^Foo($N)) {
    foo.a = 1
}

a :: proc() {
	foo: Foo(1)
	bar(&foo)
}

b :: proc() {
	foo: Foo(1)
	bar(&foo)
}
```
Running Odin check will pass majority of the time. Every so often (10-100 runs) I will get
```
will_eventually_fail.odin(8:5) 'foo' of type '^Foo(1)' has no field 'a'
        foo.a = 1
        ^~^
```
Which is incorrect.
Now if I define `Foo(1)` in a and make b define `Foo(2)` instead then I never get the error (I have done 10k + runs).
```odin
package fine

Foo :: struct($N: int) {
    a: u32,
}

bar :: proc(foo: ^Foo($N)) {
    foo.a = 1
}

a :: proc() {
	foo: Foo(1)
	bar(&foo)
}

a :: proc() {
	foo: Foo(2) // <-- the only change
	bar(&foo)
}
```

My suspicion is that all the information to resolve `Foo(1)` is being done by one thread when another thread is checking it when the type information is half completed.

### LINKED ISSUE #2679: The new nightly version seems to have some bugs
## Context

I upgraded to the newest version of Odin (nightly) and my old code would not compile.

Odin: dev-2023-07-nightly:5ac7fe45
OS:   Windows 11 Home Basic (version: 22H2), build 22621.1992
CPU:  13th Gen Intel(R) Core(TM) i9-13900HX
RAM:  32507 MiB

## Expected Behavior

I would expect my code to compile, the compiler gives me errors that make no sense.

## Current Behavior

The compiler gives me errors like:
```
Cannot assign value 'entries[index]' of type '
Octant($Holding=Empty, $Index_type=u8) (package octree)
' to '
Octant($Holding=Empty, $Index_type=u8) (package octree)
' in assignment
```

```
Cannot assign value '_get_sort_encoded(Holding, Index_type, "prune")' of type '
proc(Octant($Holding=Empty, $Index_type=u8), Octant($Holding=Empty, $Index_type=u8)) -> bool
' to '
proc(Octant($Holding=Empty, $Index_type=u8), Octant($Holding=Empty, $Index_type=u8)) -> bool
' in procedure argument
```

```
No procedures or ambiguous call for procedure group 'append' that match with the given arguments
        append(&entries, e);
        ^~~~~^
        Given argument types: (^[dynamic]Octant($Holding=Empty, $Index_type=u8), Octant($Holding=Empty, $Index_type=u8))
```

This used to work, and they types match as you can see, but it says they don't

## Failure Information (for bugs)

I currently have my directory setup like this:
```
my_game
	-> octree package (includes 2 files a test file and the octree data structure)
	-> network package (has 5 files, 1 is a test file)
	-> ...
	-> ...
```
They bugs only occure in my octree package, and they only occure when I and compiling from my game package (which include the octree package). If I "cd octree" and then compile my tests in there, they is no compliants.

### Steps to Reproduce

I could not tell you as a this only seems to be a bug in some packages and not others, and it only seems to be a bug with `odin run .` or `odin build .` , but not `odin test .`.

EDIT:

As you can see from this failure log, it can acctually compile, sometimes but it just failes like 80% and the time.
I havec experienced this before, but never as freqently as in this new release.
### Failure Logs

```

PS D:\github\Voxel_game> odin run .
D:/github/Voxel_game/Octree/Octree.odin(46:5) Error: No procedures or ambiguous call for procedure group 'append' that match with the given arguments
        append(&entries, Octant(Holding, Index_type){encoding = enc, dat ...
        ^~~~~^
        Given argument types: (^[dynamic]Octant($Holding=Empty, $Index_type=u8), Octant($Holding=Empty, $Index_type=u8))
Did you mean to use one of the following:
        runtime.append_elem        :: proc(array: ^$T/[dynamic]$E, arg: E, loc := #caller_location) -> (n: int, err: Allocator_Error)            at C:/Program Files/Odin/core/runtime/core_builtin.odin(410:1)
        runtime.append_elems       :: proc(array: ^$T/[dynamic]$E, args: ..E, loc := #caller_location) -> (n: int, err: Allocator_Error)         at C:/Program Files/Odin/core/runtime/core_builtin.odin(438:1)
        runtime.append_elem_string :: proc(array: ^$T/[dynamic]$E/u8, arg: $A/string, loc := #caller_location) -> (n: int, err: Allocator_Error) at C:/Program Files/Odin/core/runtime/core_builtin.odin(473:1)

D:/github/Voxel_game/Octree/Octree.odin(130:13) Error: No procedures or ambiguous call for procedure group 'append' that match with the given arguments
        append(&entries, e);
        ^~~~~^
        Given argument types: (^[dynamic]Octant($Holding=Empty, $Index_type=u8), Octant($Holding=Empty, $Index_type=u8))
Did you mean to use one of the following:
        runtime.append_elem        :: proc(array: ^$T/[dynamic]$E, arg: E, loc := #caller_location) -> (n: int, err: Allocator_Error)            at C:/Program Files/Odin/core/runtime/core_builtin.odin(410:1)
        runtime.append_elems       :: proc(array: ^$T/[dynamic]$E, args: ..E, loc := #caller_location) -> (n: int, err: Allocator_Error)         at C:/Program Files/Odin/core/runtime/core_builtin.odin(438:1)
        runtime.append_elem_string :: proc(array: ^$T/[dynamic]$E/u8, arg: $A/string, loc := #caller_location) -> (n: int, err: Allocator_Error) at C:/Program Files/Odin/core/runtime/core_builtin.odin(473:1)

D:/github/Voxel_game/Octree/Octree.odin(139:35) Error: Cannot assign value '_get_sort_encoded(Holding, Index_type, "prune")' of type 'proc(Octant($Holding=Empty, $Index_type=u8), Octant($Holding=Empty, $Index_type=u8)) -> bool' to 'proc(Octant($Holding=Empty, $Index_type=u8), Octant($Holding=Empty, $Index_type=u8)) -> bool' in procedure argument
        ... ies[:], _get_sort_encoded(Holding, Index_type, "prune")); ...
                    ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^

PS D:\github\Voxel_game> cd .\Octree\
PS D:\github\Voxel_game\Octree> odin run .  
D:/github/Voxel_game/Octree/Test.odin(65:27) 
Error: 'o' of type 'Octree(Empty, u8)' has no field 'entries'
        testing.expect(t, len(o.entries) == 0);
                              ^
        Suggestion: Did you mean?
                entries

D:/github/Voxel_game/Octree/Octree.odin(1:2) Error: Undefined entry point procedure 'main'

         ^
PS D:\github\Voxel_game\Octree> odin run .  
D:/github/Voxel_game/Octree/Test.odin(65:27) Error: 'o' of type 'Octree(Empty, u8)' has no field 'entries'
        testing.expect(t, len(o.entries) == 0);
                              ^
        Suggestion: Did you mean?
                entries

D:/github/Voxel_game/Octree/Octree.odin(1:2) Error: Undefined entry point procedure 'main'

         ^
PS D:\github\Voxel_game\Octree> odin run .
D:/github/Voxel_game/Octree/Test.odin(65:27) Error: 'o' of type 'Octree(Empty, u8)' has no field 'entries'
        testing.expect(t, len(o.entries) == 0);
                              ^
        Suggestion: Did you mean?
                entries

D:/github/Voxel_game/Octree/Octree.odin(1:2) Error: Undefined entry point procedure 'main'

         ^
PS D:\github\Voxel_game\Octree> odin run .
D:/github/Voxel_game/Octree/Octree.odin(1:2) Error: Undefined entry point procedure 'main'

         ^
PS D:\github\Voxel_game\Octree> odin test .        
[Package: octree]
[Test: test_1]
[test_1 : SUCCESS]
[Test: test_2]
_bin_search
[test_2 : SUCCESS]
----------------------------------------
2/2 SUCCESSFUL
PS D:\github\Voxel_game\Octree> 
```

### PR DESCRIPTION
**Pull request by rick-masters**
Fixes #2463

Also partially resolves #2679, #2814, #2949, #3200, and #3291.

The missing field problem is a thread concurrency problem with checking structure fields.
One thread is expecting another thread to populate the fields of a structure and the first thread waits until that is done.
But even after waiting, the fields are not populated.

The root cause of this problem is that the function `wait_signal_until_available` which waits for a futex is not functional.

The futex `Struct.fields_wait_signal` is a value that starts at 0 and changes to 1 to indicate completion of `check_struct_fields` for a structure. The futex is waited on by making a `SYS_futex` system call and providing the *current expected* value of the futex. The system call then returns when another thread changes the value. However, if the current futex value is *not* the current expected value that was provided, then the system call returns immediately.

So, the expectation is that the code would call `SYS_futex` with a value of 0.
However, the code is erroneously making the call (via `futex_wait`) with the value of 1 and so the call returns immediately:
https://github.com/odin-lang/Odin/blob/517d7ae0b0fd400ceb6a213e7d644c19b8088bfd/src/threading.cpp#L114-L118

One may wonder how it avoids blocking indefinitely when the futex is already 1. Well, as you can see above, it only makes the system call after checking that the futex is currently zero. I suppose this is an optimization to avoid making an unnecessary system call when the futex is already completed but doing that just so happens to avoid hanging on the completed futex as well.

Unfortunately, fixing the futex reveals that there are problems where the code waits on the futex but the futex is never set. I had to add several calls to set the futex where they were missing. Unfortunately, this means that there may be other situations not yet identified in my testing where a futex wait occurs but the futex is never signaled.

I tried to find any potential lockups by building the demo, running all the tests, and building the [ols](https://github.com/DanielGavin/ols) project. Nevertheless, this fix could possibly reveal new lockups of the compiler. If one experiences a new compiler lockup that is traced to this PR then there is probably another missing `wait_signal_set` call that needs to be tracked down.

Unfortunately, in my testing I identified a design flaw that results in a compiler lock up even when `wait_signal_set` is performed correctly. So, this PR should not be merged until that issue is evaluated.

### CODE REVIEW

**Comment by rick-masters** [comment]
The new issue revealed if this PR is merged is described in Issue #3327

File: src/threading.cpp [hunk 1]
```diff
@@ -113,7 +113,7 @@ struct Wait_Signal {
 
 gb_internal void wait_signal_until_available(Wait_Signal *ws) {
 	if (ws->futex.load() == 0) {
-		futex_wait(&ws->futex, 1);
+		futex_wait(&ws->futex, 0);
```
Comment (gingerBill) [inline src/threading.cpp:116]: Why was this changed to `0` from `1`?

**Comment by gingerBill** [comment]
I have merged this even if it completely breaks: https://github.com/odin-lang/Odin/issues/3327
